{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercheck.fullname" . }}-minio
  labels:
    {{- include "supercheck.labels" . | nindent 4 }}
    {{- include "supercheck.minio.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "supercheck.minio.selectorLabels" . | nindent 4 }}
{{- end }}
