{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercheck.fullname" . }}-redis
  labels:
    {{- include "supercheck.labels" . | nindent 4 }}
    {{- include "supercheck.redis.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "supercheck.redis.selectorLabels" . | nindent 4 }}
{{- end }}
