{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercheck.fullname" . }}-worker
  labels:
    {{- include "supercheck.labels" . | nindent 4 }}
    {{- include "supercheck.worker.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "supercheck.worker.selectorLabels" . | nindent 4 }}
{{- end }}
